import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className="flex items-start justify-center min-h-screen px-4 py-4 bg-slate-900">
      <Head>
        <title>Sandbox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <div className="flex flex-row items-start w-screen h-full px-6">
          <h1 className="text-xl font-medium text-slate-100">🏗&nbsp;&nbsp;Sandbox</h1>
        </div>
      </main>

    </div>
  )
}

export default Home
